# Generated by Django 3.2 on 2022-03-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
